### ISSUE TITLE
Unintentional cancellation on inputs

### ISSUE THREAD

**Issue by Lezrec** [ANadig/YellowFruit#3]
Clicking on the grayed-out area outside of the input window will close the input window without warning or saving the inputs. This leads to unintentional cancellation of inputting information such as teams and matches, especially exacerbated by the proximity of the save button to the edge of the window.
![Annotation 2019-10-12 154243](https://user-images.githubusercontent.com/16161944/66707999-f35c2600-ed06-11e9-929e-aa7003671563.png)

**Comment by ANadig** [comment]
fixed
